version: "3.8"
services:
    backend:
      environment:
        FRONTEND_URL: "https://3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
        BACKEND_URL:  "https://4576-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
        OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io"
        OTEL_EXPORTER_OTLP_HEADERS: "x-honeycomb-team=UlXq9J9JYTTFLi4nzfIAsA"
        OTEL_SERVICE_NAME: "backend-flask"
      build: ./backend-flask
      image: backend-flask:v1
      container_name: backend-dev-container
      ports:
        - "4576:5000"
      volumes:
        - ./backend-flask:/backend-flask
    
    frontend:
      build: ./frontend-react-js
      image: frontend-react-js:v1
      container_name: frontend-dev-container
      environment:
        REACT_APP_BACKEND_URL: "https://4576-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
        REACT_APP_AWS_PROJECT_REGION: "${AWS_DEFAULT_REGION}"
        REACT_APP_AWS_COGNITO_REGION: "${AWS_DEFAULT_REGION}"
        REACT_APP_AWS_USER_POOLS_ID: us-east-1_rKGsdF0uG
        REACT_APP_CLIENT_ID: 105gm5559nmjctoirp45020be0

      ports:
        - "3000:3000"
      volumes:
        - ./frontend-react-js:/frontend-react-js
    
      
networks: 
    internal-network:
      driver: bridge
      name: cruddur